USE hippo_anthony;


INSERT INTO albums_migration (artist, name, release_date, sales, genre)
VALUES
  ('Shania Twain', 'Come On Over', 1997, 30.4, 'Country, pop'),
  ('Pink Floyd', 'The Dark Side of the Moon', 1973, 24.8, 'Progressive rock'),
  ('Meat Loaf', 'Bat Out of Hell', 1977, 22, 'Hard rock, glam rock, progressive rock'),
  ('Michael Jackson', 'Thriller', 1982, 51.2, 'Pop, post-disco, funk, rock'),
  ('Whitney Houston / various artists', 'The Bodyguard', 1992, 28.7, 'R&B, soul, pop, soundtrack'),
  ('Fleetwood Mac', 'Rumours', 1977, 30.3, 'Soft rock'),
  ('Eagles', 'Their Greatest Hits (1971–1975)', 1976, 41.2, 'Country rock, soft rock, folk rock'),
  ('Eagles', 'Hotel California', 1976, 31.8, 'Soft rock'),
  ('Bee Gees / Various artists', 'Saturday Night Fever', 1977, 22.1, 'Disco'),
  ('AC/DC', 'Back in Black', 1980, 30.1, 'Hard rock'),
  ('Led Zeppelin', 'Led Zeppelin IV', 1971, 30.4, 'Hard rock, heavy metal, folk rock'),
  ('Michael Jackson', 'Bad', 1987, 21.2, 'Pop, rhythm and blues, funk and rock'),
  ('Alanis Morissette', 'Jagged Little Pill', 1995, 25.4, 'Alternative rock'),
  ('Various artists', 'Dirty Dancing', 1987, 24.1, 'Pop, rock, R&B'),
  ('Celine Dion', 'Falling into You', 1996, 21.1, 'Pop, soft rock'),
  ('Adele', '21', 2011, 27.1, 'Pop, soul'),
  ('The Beatles', '1', 2000, 23.2, 'Rock'),
  ('Metallica', 'Metallica', 1991, 22.7, 'Heavy metal'),
  ('Celine Dion', 'Let\'s Talk About Love', 1997, 20.5, 'Pop, soft rock'),
  ('Bob Marley and the Wailers', 'Legend: The Best of Bob Marley & The Wailers', 1984, 22.9, 'Reggae'),
  ('Guns N\' Roses', 'Appetite for Destruction', 1987, 22.8, 'Hard rock'),
  ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 22, 'Heartland rock'),
  ('ABBA', 'Gold: Greatest Hits', 1992, 21.6, 'Pop, disco'),
  ('Dire Straits', 'Brothers in Arms', 1985, 21.1, 'Roots rock, blues rock, soft rock'),
  ('Madonna', 'The Immaculate Collection', 1990, 20.8, 'Pop, dance'),
  ('Santana', 'Supernatural', 1999, 20.8, 'Latin rock'),
  ('Pink Floyd', 'The Wall', 1979, 18.9, 'Progressive rock'),
  ('The Beatles', 'Sgt. Pepper\'s Lonely Hearts Club Band', 1967, 18.3, 'Rock'),
  ('Michael Jackson', 'Dangerous', 1991, 17.0, 'New jack swing, R&B and pop'),
  ('The Beatles', 'Abbey Road', 1969, 16.9, 'Rock'),
  ('Norah Jones', 'Come Away with Me', 2002, 19.9, 'Jazz'),
  ('Mariah Carey', 'Music Box', 1993, 17.8, 'Pop, R&B'),
  ('Various artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 15, 'Rock and roll'),
  ('Eminem', 'The Eminem Show', 2002, 19.1, 'Hip hop'),
  ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'Film score'),
  ('Britney Spears', '...Baby One More Time', 1999, 19.9, 'Pop'),
  ('Nirvana', 'Nevermind', 1991, 17.8, 'Grunge, alternative rock'),
  ('Eric Clapton', 'Unplugged', 1992, 17, 'Acoustic rock, acoustic blues'),
  ('Queen', 'Greatest Hits', 1981, 20.6, 'Rock'),
  ('Phil Collins', 'No Jacket Required', 1985, 17.7, 'Pop rock'),
  ('Whitney Houston', 'Whitney Houston', 1985, 17.6, 'Pop, R&B'),
  ('Eminem', 'The Marshall Mathers LP', 2000, 17.5, 'Hip hop'),
  ('Linkin Park', 'Hybrid Theory', 2000, 17.2, 'Nu metal, rap metal, alternative metal'),
  ('U2', 'The Joshua Tree', 1987, 16.7, 'Rock'),
  ('Prince and The Revolution', 'Purple Rain', 1984, 15.7, 'Pop rock, new wave, R&B'),
  ('Bon Jovi', 'Slippery When Wet', 1986, 15.3, 'Hard rock, glam metal'),
  ('Carole King', 'Tapestry', 1971, 15.1, 'Pop'),
  ('Madonna', 'True Blue', 1986, 14.5, 'Pop, dance'),
  ('Simon & Garfunkel', 'Bridge over Troubled Water', 1970, 12.5, 'Folk rock'),
  ('George Michael', 'Faith', 1987, 13.9, 'Pop, R&B, funk, soul'),
  ('Elton John', 'Greatest Hits', 1974, 19.1, 'Pop'),
  ('Backstreet Boys', 'Millennium', 1999, 18.4, 'Pop'),
  ('Adele', '25', 2015, 19, 'Soul, pop, R&B'),
  ('Spice Girls', 'Spice', 1996, 16.4, 'Pop'),
  ('Ace of Base', 'Happy Nation/The Sign', 1993, 14.4, 'Pop'),
  ('Michael Jackson', 'HIStory: Past, Present and Future, Book I', 1995, 15.2, 'R&B, pop and hip hop'),
  ('Celine Dion', 'All the Way... A Decade of Song', 1999, 14.4, 'Pop'),
  ('Madonna', 'Like a Virgin', 1984, 16.2, 'Pop, dance'),
  ('Bon Jovi', 'Cross Road', 1994, 11.6, 'Hard rock, glam metal'),
  ('Elvis Presley', 'Elvis\' Christmas Album', 1957, 20.8, 'Christmas, pop, gospel, rock and roll'),
  ('Boston', 'Boston', 1976, 18.1, 'Arena rock, hard rock'),
  ('Mariah Carey', 'Daydream', 1995, 15.2, 'Pop, R&B'),
  ('Green Day', 'Dookie', 1994, 14.6, 'Pop punk, punk rock, alternative rock'),
  ('Whitney Houston', 'Whitney', 1987, 14.5, 'Pop, R&B'),
  ('Shania Twain', 'The Woman in Me', 1995, 14.5, 'Country, pop'),
  ('Britney Spears', 'Oops!... I Did It Again', 2000, 14.4, 'Pop'),
  ('Def Leppard', 'Hysteria', 1987, 13.9, 'Hard rock, glam metal'),
  ('Lauryn Hill', 'The Miseducation of Lauryn Hill', 1998, 13.7, 'Neo Soul, R&B and Hip Hop'),
  ('Tracy Chapman', 'Tracy Chapman', 1988, 13.3, 'Folk rock'),
  ('Lionel Richie', 'Can\'t Slow Down', 1983, 12.3, 'Pop, R&B, soul'),
  ('Michael Jackson', 'Off the Wall', 1979, 11.7, 'Disco, pop, funk and R&B'),
  ('Fugees', 'The Score', 1996, 11.6, 'Alternative hip hop'),
  ('Oasis', '(What\'s the Story) Morning Glory?', 1995, 11.6, 'Britpop, rock'),
  ('Celine Dion', 'The Colour of My Love', 1993, 11.1, 'Pop'),
  ('Elton John', 'Goodbye Yellow Brick Road', 1973, 9.6, 'rock, pop rock, glam rock'),
  ('Pink Floyd', 'Wish You Were Here', 1975, 9.2, 'Progressive rock, art rock, experimental rock');

